
import random    
frasesDiarias = [
    "La puerta de mi corazón se abre hacia dentro. Paso del rencor al Amor.",
    "Hoy escucho mis sentimientos y soy amable conmigo mismo. Sé que todos mis sentimientos son mis amigos",
    "El pasado ha terminado, ya no tiene poder en el presente. Los pensamientos de Este Momento crean mi futuro.",
    "No es divertido ser una victima. Rechazo volver a sentirme una persona indefensa.",
    "Reclamo mi fuerza.",
    "Me concedo el don de librarme del pasado y me adentro con júbilo en el Ahora.",
    "Consigo la ayuda que necesito, y ésta puede llegar de cualquier parte. Mi sistema de apoyo es sólido y afectuoso a la vez.",
    "No hay problema, ni demasiado grande ni demasiado pequeño, que el amor no pueda resolver.",
    "Estoy dispuesto a curarme. Estoy dispuesto a perdonar. Todo está bien.",
    "Cuando cometo una equivocación, me doy cuenta que no es más que una parte de mi proceso de aprendizaje.",
    "Paso del perdón a la comprensión y siento compasión por todos.",
    "Cada día me ofrece una nueva oportunidad. El ayer ya ha concluido. Hoy es el primer día de mi futuro.",
    "Sé que los viejos patrones negativos ya no me limitan. Me despojo de ellos sin esfuerzo.",
    "Soy capaz de perdonar; soy afable. afectuoso y amable, y sé que la Vida me ama.",
    "Al perdonarme a mí mismo me resulta más fácil perdonar a los demás.",
    "Amo y acepto a todos los miembros de mi familia tal como son ahora mismo.",
    "Me perdono por no ser una persona perfecta. Vivo de la mejor manera que sé.",
    "No puedo cambiar a otras personas. Dejo a los demás ser como son y simplemente me amo tal como soy.",
    "Me libero en este momento de todos los traumas de mi infancia y vivo en el amor-",
    "Sé que no me puedo responsabilizar de otras personas. Todos estamos bajo la ley de nuestra propia conciencia.",
    "Todas las personas tienen algo que enseñarme. Hay un propósito para que estemos juntos.",
    "Perdono a todas las personas de mi pasado que me han infligido algún daño. Las libero con amor.",
    "Todos los cambios que tengo ante mí en la vida son positivos.frases Louise Hay",
    "Abandono todo el miedo y la duda; la vida se vuelve sencilla y fácil para mí.",
    "Creo un mundo libre de estrés para mí",
    "Soy una persona capaz y puedo hacer frente a cualquier cosa.",
    "Me siento seguro cuando expreso mis sentimientos. Puedo estar sereno en cualquier situación.",
    "Me deshago de mis temores de la infancia. Me siento seguro, soy un ser humano con poder.",
    "Me hallo en el proceso de hacer cambios positivos en mi vida.",
    "Dejo ir toda la negatividad que hay en mi cuerpo y mi mente.",
    "Estoy dispuesto a aprender. Mientras más aprendo, más evoluciono.",
    "No importa mi edad, siempre puedo aprender y lo hago con decisión.",
    "Poseo la fuerza para permanecer en calma ante cualquier situación.",
    "Cierro los ojos, tengo pensamientos positivos e inhalo y exhalo bondad.",
    "Me amo tal y como soy, ya no aspiro a ser perfecto para amarme.",
    "El mejor regalo que puedo hacerme es mi amor incondicional.",
    "Tengo la autoestima, el poder y la confianza suficientes para avanzar en la vida sin dificultad",
    "Elijo sentirme bien respecto a mí mismo. Me merezco mi amor.",
    "No importa lo que digan o hagan los demás. #Lo que importa es cómo elijo reaccionar y lo que elijo creer acerca de  mí mismo.",
    "Estoy dispuesto a deshacerme de cualquier necesidad de lucha o sufrimiento. Merezco todo lo bueno.",
    "Hoy, ninguna persona, lugar o cosa puede irritarme o enojarme. Elijo estar en paz.",
    "Mi conciencia está llena de pensamientos saludables, positivos y amorosos que se reflejan en mi experiencia.",
    "Avanzo en la vida, sé que estoy a salvo y que cuento con la protección y guía Divina.",
    "Expreso gratitud por todo el bien de mi vida. #Cada día me aporta maravillosas sorpresas nuevas.",
    "Cuanto más agradecido estoy por la riqueza y abundancia en mi vida, más razones tengo para estarlo.",
    "La abundancia fluye libremente a través de mí. Merezco lo mejor y acepto lo mejor ahora.",
    "La vida satisface todas mis necesidades en abundancia. Confío en la Vida.",
    "Sé que puedo hacer Milagros en mi Vida.",
    "Mi corazón es el centro de mi poder. Sigo a mi corazón.",
    "Me siento seguro y realizado en todo lo que hago.",
    "Comienza hoy mismo a hablarte con amor y a vibrar en sintonía con un Universo deseoso de regalarte",
]

def frase():
    return frasesDiarias[random.randint(0, 50)]